// export const MENU = [
//   {
//     id: 1,
//     href: '/introduction',
//     label: 'はじめに',
//     pageActive: 0,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/introduction/neo-gold-money',
//         label: 'Neo Gold Money LLC社員権',
//         pageActive: 1,
//       },
//       {
//         id: 2,
//         href: '/introduction/purpose-of-fundraising',
//         label: '資金調達の目的',
//         pageActive: 2,
//       },
//       {
//         id: 3,
//         href: '/introduction/return-on-investment-target',
//         label: '投資利益率目標',
//         pageActive: 3,
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: 'our-mission',
//     href: '/our-mission',
//     label: 'Our Mission',
//     pageActive: 4,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/our-mission',
//         label: '',
//         pageActive: 5,
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: 'why-gold-now',
//     href: '/why-gold-now',
//     label: 'Why Gold Now',
//     pageActive: 6,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/our-mission',
//         label: '',
//         pageActive: 7,
//       },
//     ],
//   },
//   {
//     id: 4,
//     name: 'who-we-are',
//     href: '/who-we-are',
//     label: 'Who We Are',
//     pageActive: 8,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/who-we-are/neo-gold-money',
//         label: 'Neo Gold Money LLC',
//         pageActive: 9,
//       },
//       {
//         id: 2,
//         href: '/who-we-are/johnDwaihe',
//         label: 'John David Waihe’e lll',
//         pageActive: 10,
//       },
//       {
//         id: 3,
//         href: '/who-we-are/johnDwaihe',
//         label: '',
//         pageActive: 11,
//       },
//       {
//         id: 4,
//         href: '/who-we-are/outline-of-the-first-project',
//         label: '第一号プロジェクト概要',
//         pageActive: 12,
//       },
//     ],
//   },
//   {
//     id: 5,
//     name: 'information',
//     href: '/information',
//     label: '金鉱山情報',
//     pageActive: 13,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/information/mckinley-mine',
//         label: 'Mckinley Mine',
//         pageActive: 14,
//       },
//       {
//         id: 2,
//         href: '/information/mckinley-mine',
//         label: '',
//         pageActive: 15,
//       },
//       {
//         id: 3,
//         href: '/information/characteristics-reserves',
//         label: '特徴と埋蔵量',
//         pageActive: 16,
//       },

//       {
//         id: 4,
//         href: '/information/characteristics-reserves',
//         label: '',
//         pageActive: 17,
//       },
//       {
//         id: 5,
//         href: '/information/characteristics-reserves',
//         label: '',
//         pageActive: 18,
//       },
//       {
//         id: 6,
//         href: '/information/characteristics-reserves',
//         label: '',
//         pageActive: 19,
//       },
//       {
//         id: 7,
//         href: '/information/partner',
//         label: 'パートナー',
//         pageActive: 20,
//       },
//       {
//         id: 8,
//         href: '/information/development-schedule',
//         label: '開発スケジュール',
//         pageActive: 21,
//       },
//     ],
//   },
//   {
//     id: 6,
//     name: 'revenue-plan',
//     href: '/revenue-plan',
//     label: '収益プラン',
//     pageActive: 22,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/revenue-plan/revenue-plan-2',
//         label: '収益プラン',
//         pageActive: 23,
//       },
//       {
//         id: 2,
//         href: '/revenue-plan/distribution-schedule',
//         label: '分配スケジュール',
//         pageActive: 24,
//       },
//       {
//         id: 3,
//         href: '/revenue-plan/key-indicators',
//         label: '重要指標',
//         pageActive: 25,
//       },
//     ],
//   },
//   {
//     id: 7,
//     name: 'gold-price-future',
//     href: '/gold-price-future',
//     label: '金価格の今後',
//     pageActive: 26,
//     sub_menu: [
//       {
//         id: 1,
//         href: '/gold-price-future/gold-price',
//         label: '金価格の今後',
//         pageActive: 27,
//       },
//       {
//         id: 2,
//         href: '/gold-price-future/gold-price-and-earnings',
//         label: '金価格と収益',
//         pageActive: 28,
//       },
//       {
//         id: 3,
//         href: '/gold-price-future/john-paulson-prediction',
//         label: 'ジョン・ポールソン予測',
//         pageActive: 29,
//       },
//       {
//         id: 4,
//         href: '/gold-price-future/jim-roger-prediction',
//         label: 'ジム・ロジャー予測',
//         pageActive: 30,
//       },
//       {
//         id: 5,
//         href: '/gold-price-future/news',
//         label: 'ニュース',
//         pageActive: 31,
//       },
//       {
//         id: 6,
//         href: '/gold-price-future/references',
//         label: '参考文献',
//         pageActive: 32,
//       },
//       {
//         id: 7,
//         href: '/gold-price-future/references',
//         label: '',
//         pageActive: 33,
//       },
//     ],
//   },
// ];

export const MENU = [
  { id: 1, href: '/', label: '', pageActive: 0 },
  {
    id: 2,
    href: '/introduction',
    label: 'はじめに',
    pageActive: 1,
    sub_menu: [
      {
        id: 1,
        href: '/introduction/neo-gold-money',
        label: 'Neo Gold Money LLC社員権',
        pageActive: 2,
      },
      {
        id: 2,
        href: '/introduction/purpose-of-fundraising',
        label: '資金調達の目的',
        pageActive: 3,
      },
      {
        id: 3,
        href: '/introduction/return-on-investment-target',
        label: '投資利益率目標',
        pageActive: 4,
      },
    ],
  },
  {
    id: 3,
    name: 'our-mission',
    href: '/our-mission',
    label: 'Our Mission',
    pageActive: 5,
    sub_menu: [
      {
        id: 1,
        href: '/our-mission-content',
        label: '',
        pageActive: 6,
      },
    ],
  },
  {
    id: 4,
    name: 'why-gold-now',
    href: '/why-gold-now',
    label: 'Why Gold Now',
    pageActive: 7,
    sub_menu: [
      {
        id: 1,
        href: '/why-gold-now-content',
        label: '',
        pageActive: 8,
      },
    ],
  },
  {
    id: 5,
    name: 'who-we-are',
    href: '/who-we-are',
    label: 'Who We Are',
    pageActive: 9,
    sub_menu: [
      {
        id: 1,
        href: '/who-we-are/neo-gold-money',
        label: 'Neo Gold Money LLC',
        pageActive: 10,
      },
      {
        id: 2,
        href: '/who-we-are/johnDwaihe',
        label: 'John David Waihe’e lll',
        pageActive: 11,
      },
      {
        id: 3,
        href: '/who-we-are/johnDwaihe',
        label: '',
        pageActive: 12,
      },
      {
        id: 4,
        href: '/who-we-are/outline-of-the-first-project',
        label: '第一号プロジェクト概要',
        pageActive: 13,
      },
    ],
  },
  {
    id: 6,
    name: 'information',
    href: '/information',
    label: '金鉱山情報',
    pageActive: 14,
    sub_menu: [
      {
        id: 1,
        href: '/information/mckinley-mine',
        label: 'Mckinley Mine',
        pageActive: 15,
      },
      {
        id: 2,
        href: '/information/mckinley-mine',
        label: '',
        pageActive: 16,
      },
      {
        id: 3,
        href: '/information/characteristics-reserves',
        label: '特徴と埋蔵量',
        pageActive: 17,
      },

      {
        id: 4,
        href: '/information/characteristics-reserves',
        label: '',
        pageActive: 18,
      },
      {
        id: 5,
        href: '/information/characteristics-reserves',
        label: '',
        pageActive: 19,
      },
      {
        id: 6,
        href: '/information/characteristics-reserves',
        label: '',
        pageActive: 20,
      },
      {
        id: 7,
        href: '/information/partner',
        label: 'パートナー',
        pageActive: 21,
      },
      {
        id: 8,
        href: '/information/development-schedule',
        label: '開発スケジュール',
        pageActive: 22,
      },
    ],
  },
  {
    id: 7,
    name: 'revenue-plan',
    href: '/revenue-plan',
    label: '収益プラン',
    pageActive: 23,
    sub_menu: [
      {
        id: 1,
        href: '/revenue-plan/revenue-plan-2',
        label: '収益プラン',
        pageActive: 24,
      },
      {
        id: 2,
        href: '/revenue-plan/distribution-schedule',
        label: '分配スケジュール',
        pageActive: 25,
      },
      {
        id: 3,
        href: '/revenue-plan/key-indicators',
        label: '重要指標',
        pageActive: 26,
      },
    ],
  },
  {
    id: 8,
    name: 'gold-price-future',
    href: '/gold-price-future',
    label: '金価格の今後',
    pageActive: 27,
    sub_menu: [
      {
        id: 1,
        href: '/gold-price-future/gold-price',
        label: '金価格の今後',
        pageActive: 28,
      },
      {
        id: 2,
        href: '/gold-price-future/gold-price-and-earnings',
        label: '金価格と収益',
        pageActive: 29,
      },
      {
        id: 3,
        href: '/gold-price-future/john-paulson-prediction',
        label: 'ジョン・ポールソン予測',
        pageActive: 30,
      },
      {
        id: 4,
        href: '/gold-price-future/jim-roger-prediction',
        label: 'ジム・ロジャー予測',
        pageActive: 31,
      },
      {
        id: 5,
        href: '/gold-price-future/news',
        label: 'ニュース',
        pageActive: 32,
      },
      {
        id: 6,
        href: '/gold-price-future/references',
        label: '参考文献',
        pageActive: 33,
      },
      {
        id: 7,
        href: '/home',
        label: '',
        pageActive: 34,
      },
    ],
  },
];
